### ISSUE TITLE
Update the front page readme

### ISSUE THREAD

**Issue by HeckerBirb** [HeckerBirb/infosec-manual#12]
Should include:
* High level overview
* What to expect as a business owner / blue-teamer
* What to expect as a pentester / red-teamer

**Comment by spacemonkey1101** [comment]
Can  i work on it?

**Comment by HeckerBirb** [comment]
Hi @spacemonkey1101 thanks for your interest :)
I prefer to update this page myself so that the clear direction can be better visualised. I expect this to happen during today. If you would like please feel free to help out with one of the unassigned tasks :)

Cheers! 💯
